export class MasterBase<T> {
  value: T | undefined;
  key: string;
  label: string;
  required: boolean;
  order: number;
  controlType: string;
  type: string;
  options: { key: string, value: string }[];
  className: string;
  pattern: string;
  disabled: boolean;
  icon: string;
  validatetype: string;
  maxlength: string;
  targetid: string;
  changeinput: string;
  tooltip: string;
  errmsg: string;
  hidden: boolean;
  showonchng: boolean;
  onchngshow: boolean;
  altctrl: boolean;
  grpname: string;
  constructor(fields: {
    value?: T;
    key?: string;
    label?: string;
    required?: boolean;
    order?: number;
    controlType?: string;
    type?: string;
    options?: { key: string, value: string }[];
    className?: string;
    pattern?: string;
    disabled?: true;
    icon?: string;
    validatetype?: string;
    maxlength?: string;
    targetid?: string;
    changeinput?: string;
    tooltip?: string;
    errmsg?: string;
    hidden?: boolean;
    showonchng?: boolean;
    onchngshow?: boolean;
    altctrl?: boolean;
    grpname?: string;
  } = {}) {
    this.value = fields.value;
    this.key = fields.key || '';
    this.label = fields.label || '';
    this.required = fields.required || false;
    this.order = fields.order === undefined ? 1 : fields.order;
    this.controlType = fields.controlType || '';
    this.type = fields.type || '';
    this.options = fields.options || [];
    this.className = fields.className || 'col-xl-12 col-lg-12 col-md-12 col-sm-12 mb-2';
    this.pattern = fields.pattern || '';
    this.disabled = fields.disabled || false;
    this.icon = fields.icon || '';
    this.validatetype = fields.validatetype || 'alphaumeric';
    this.maxlength = fields.maxlength || '50';
    this.targetid = fields.targetid || '';
    this.changeinput = fields.changeinput || '';
    this.tooltip = fields.tooltip || '';
    this.errmsg = fields.errmsg || '';
    this.hidden = fields.hidden || false;
    this.showonchng = fields.showonchng || false;
    this.onchngshow = fields.onchngshow || false;
    this.altctrl = fields.altctrl || false;
    this.grpname = fields.grpname || '';
  }
}